### ISSUE TITLE
Handling dependent form fields

### ISSUE THREAD

**Issue by spidergears** [dgonz64/react-hook-form-auto#16]
Is there a way to handle dependent form fields?
Examples: 
1. Show or hide fields based on the value from a select field
2. Updating options for states selection based on country selected

Any suggestions or workarounds?

**Comment by dgonz64** [comment]
It's not implemented yet and I don't come up with non convoluted workarounds. I'm thinking about enabling a new attribute in the schema called something like `onChange` that will allow to update the schema for that field. Let me study it and I will get back to you.

**Comment by dgonz64** [comment]
Sorry for the delay. After a careful study of the problem, I thought the cleanest way was to update to React Hook Form 7 and intercept react-hook-form `onChange`.

Following 1.3.0 release you can use the `onChange` attribute in the schemas. It will receive the value and a context object that allows you to change form state. Find the example and documentation [here](docs/schema-onchange.md).

If you made your own skin or used `skinOverride`, you will need to make some changes in your skin code. Sorry about that, I hope [this migration guide](docs/migrate-1.2-to-1.3.md) helps.

This implementation is still experimental (even lacks tests), so please, tell me about your experience with it or if you encounter any problems.

**Comment by spidergears** [comment]
Hi thanks for your response. This surely helps.

Does setting field visibility `setVisible` to false only hides the fields from render or does it also remove the field from DOM and formState? 

If not, does the lib currently provide any other helpers to add/remove formFields dynamically

**Comment by dgonz64** [comment]
Hello and thanks to you!

Following `1.3.5` version, already published, `setVisible` makes the field disappear from submitted doc when not visible.

It doesn't remove the field from the state but hides its value while coercing (always done when submitting).
